datagrid:
    audit-grid:
        source:
            acl_resource: oro_dataaudit_history
            type: orm
            query:
                select:
                    - a.id
                    - a.action
                    - a.version
                    - a.objectClass
                    - a.objectName
                    - a.objectId
                    - a.data
                    - a.loggedAt
                    - u.id
                    - >
                      CONCAT(
                        CONCAT(
                            CONCAT(u.firstName, ' '),
                            CONCAT(u.lastName, ' ')
                        ),
                        CONCAT(' - ', u.email)
                      ) as author
                from:
                    - { table: OroDataAuditBundle:Audit, alias: a }
                join:
                    left:
                        user:
                            join: a.user
                            alias: u

        columns:
            action:
                label: Action
                type: field
                frontend_type: string
            version:
                label: Version
                type: field
                frontend_type: string
            objectClass:
                label: Object class
                type: field
                frontend_type: string
            objectName:
                label: Object name
                type: field
                frontend_type: string
            objectId:
                label: Object id
                type: field
                frontend_type: integer
            data:
                label: Data
                type: twig
                template: OroDataAuditBundle:Datagrid:Property/data.html.twig
                frontend_type: string
            author:
                label: Author
                type: field
                frontend_type: string
            loggedAt:
                label: Logged at
                type: field
                frontend_type: date

        properties: ~
        sorters:
            columns:
                action:
                    data_name: a.action
                version:
                    data_name: a.version
                objectClass:
                    data_name: a.objectClass
                objectName:
                    data_name: a.objectName
                objectId:
                    data_name: a.objectId
                data:
                    data_name: a.data
                author:
                    data_name: author
                loggedAt:
                    data_name: a.loggedAt
            default: ~

        filters:
            columns:
                action:
                    type: choice
                    data_name: a.action
                    choices:
                        update: Updated
                        create: Created
                        remove: Deleted
                version:
                    type: number
                    data_name: a.version
                objectClass:
                    type: choice
                    data_name: a.objectClass
                objectName:
                    type: string
                    data_name: a.objectName
                objectId:
                    type: number
                    data_name: a.objectId
                data:
                    type: string
                    data_name: a.data
                author:
                    type: string
                    data_name: author
                loggedAt:
                    type: datetime
                    data_name: u.loggedAt

    audit-history-grid:
        source:
            acl_resource: oro_dataaudit_history
            type: orm
            query:
                select:
                    - a.id
                    - a.data as data
                    - a.loggedAt
                    - >
                      CONCAT(
                        CONCAT(
                            CONCAT(u.firstName, ' '),
                            CONCAT(u.lastName, ' ')
                        ),
                        CONCAT(' - ', u.email)
                      ) as author
                from:
                    - { table: OroDataAuditBundle:Audit, alias: a }
                join:
                    left:
                        user:
                            join: a.user
                            alias: u
                where:
                    and:
                        - a.objectClass = :objectClass AND a.objectId = :objectId
        columns:
            author:
                label: Author
                type: field
                frontend_type: string
            loggedAt:
                label: Logged at
                type: field
                frontend_type: date
            old:
                label: Old values
                type: twig
                template: OroDataAuditBundle:Datagrid:Property/old.html.twig
                frontend_type: string
                data_name: data
            new:
                label: New values
                type: twig
                template: OroDataAuditBundle:Datagrid:Property/new.html.twig
                frontend_type: string
                data_name: data
        properties: ~
        sorters:
            columns:
                author:
                    data_name: author
                loggedAt:
                    data_name: a.loggedAt
            default:
                loggedAt: %oro_grid.extension.orm_sorter.class%::DIRECTION_DESC

        filters: ~
