parameters:
    oro_dataaudit.datagrid.manager.class:         Oro\Bundle\DataAuditBundle\Datagrid\AuditDatagridManager
    oro_dataaudit.history.datagrid.manager.class: Oro\Bundle\DataAuditBundle\Datagrid\AuditHistoryDatagridManager

services:
    oro_dataaudit.datagrid.manager:
        class:                                  %oro_dataaudit.datagrid.manager.class%
        tags:
            - name:                             oro_grid.datagrid.manager
              datagrid_name:                    audit
              entity_name:                      Oro\Bundle\DataAuditBundle\Entity\Audit
              entity_hint:                      audit
              route_name:

              query_entity_alias:               a

    oro_dataaudit.history.datagrid.manager:
        class:                                  %oro_dataaudit.history.datagrid.manager.class%
        tags:
            - name:                             oro_grid.datagrid.manager
              datagrid_name:                    history
              entity_name:                      Oro\Bundle\DataAuditBundle\Entity\Audit
              entity_hint:                      history
              route_name:                       oro_dataaudit_history
              query_entity_alias:               a
