oro_entity_config:
    dataaudit:
#        entity:
#            items:
#                auditable:
#                    grid:
#                        type:               boolean
#                        label:              'Auditable'
#                        filter_type:        oro_grid_orm_boolean
#                        required:           true
#                        sortable:           true
#                        filterable:         true
#                        show_filter:        false
#                    form:
#                        type:               choice
#                        options:
#                            choices:        ['No', 'Yes']
#                            empty_value:    false
#                            block:          auditable
#                            label:          'Auditable'
#        field:
#            items:
#                auditable:
#                    priority:               60
#                    parent_value:
#                        name:               auditable
#                        value:              true
#                    grid:
#                        type:               boolean
#                        label:              'Auditable'
#                        filter_type:        oro_grid_orm_boolean
#                        required:           true
#                        sortable:           true
#                        filterable:         false
#                        show_filter:        false
#                    form:
#                        type:               choice
#                        options:
#                            choices:        ['No', 'Yes']
#                            empty_value:    false
#                            block:          auditable
#                            label:          'Auditable'
