oro_menu_config:
    items:
        audit_list:
            label: 'Data Audit'
            route: 'oro_dataaudit_index'
            extras:
                position:    70
                routes:      ['oro_dataaudit_*']
                description: 'Data Audit'

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        audit_list: ~

oro_titles:
    oro_dataaudit_index: ~
