parameters:
    oro_dataaudit.loggable.entity.class:            'Oro\Bundle\DataAuditBundle\Entity\Audit'
    oro_dataaudit.loggable.entity_field.class:      'Oro\Bundle\DataAuditBundle\Entity\AuditField'

services:
    oro_dataaudit.filter.audit:
        class: 'Oro\Bundle\DataAuditBundle\Filter\AuditFilter'
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@oro_query_designer.query_designer.manager'
        tags:
            - { name: 'oro_filter.extension.orm_filter.filter', type: 'audit' }

    oro_dataaudit.loggable.audit_entity_mapper:
        class: 'Oro\Bundle\DataAuditBundle\Loggable\AuditEntityMapper'
        calls:
            - ['addAuditEntryClass', ['%oro_user.entity.class%', '%oro_dataaudit.loggable.entity.class%']]
            - ['addAuditEntryFieldClass', ['%oro_user.entity.class%', '%oro_dataaudit.loggable.entity_field.class%']]

    oro_dataaudit.listener.send_changed_entities_to_message_queue:
        class: 'Oro\Bundle\DataAuditBundle\EventListener\SendChangedEntitiesToMessageQueueListener'
        arguments:
            - '@oro_message_queue.message_producer'
            - '@security.token_storage'
        tags:
            - { name: 'doctrine.event_subscriber', priority: -255 }

    # BC if some one used this service name to disable an audit listnere
    oro_dataaudit.listener.entity_listener:
        alias: oro_dataaudit.listener.send_changed_entities_to_message_queue

    oro_dataaudit.dataaudit_grid_service:
        class: 'Oro\Bundle\DataAuditBundle\EventListener\AuditGridListener'
        arguments:
            - '@doctrine.orm.entity_manager'

    oro_dataaudit.event_listener.dataaudit_history_grid_listener:
        class: 'Oro\Bundle\DataAuditBundle\EventListener\AuditHistoryGridListener'
        arguments:
            - ['objectClass', 'objectId']
        tags:
          - { name: 'kernel.event_listener', event: 'oro_datagrid.datagrid.build.after.audit-history-grid', method: 'onBuildAfter' }

    oro_dataaudit.event_listener.segment_widget_options_listener:
        class: 'Oro\Bundle\DataAuditBundle\EventListener\SegmentWidgetOptionsListener'
        arguments:
            - '@http_kernel'
            - '@oro_security.security_facade'
            - '@oro_dataaudit.segment_widget.context_checker'
        calls:
            - ['setRequest', ["@?request="]]
        tags:
            - { name: 'kernel.event_listener', event: 'oro_segment.widget_options_load', method: 'onLoad' }

    oro_dataaudit.event_listener.segment_condition_builder_options_listener:
        class: 'Oro\Bundle\DataAuditBundle\EventListener\SegmentConditionBuilderOptionsListener'
        tags:
            - { name: 'kernel.event_listener', event: 'oro_segment.condition_builder_options_load', method: 'onLoad' }

    # Placeholder filter
    oro_dataaudit.placeholder.filter:
        class: 'Oro\Bundle\DataAuditBundle\Placeholder\AuditableFilter'
        arguments:
            - '@oro_entity_config.provider.dataaudit'

    oro_dataaudit.audit.manager.api:
        class: 'Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager'
        parent: 'oro_soap.manager.entity_manager.abstract'
        arguments:
            - '%oro_dataaudit.loggable.entity.class%'
            - '@doctrine.orm.entity_manager'

    oro_dataaudit.migration.extension.audit_field:
        class: 'Oro\Bundle\DataAuditBundle\Migration\Extension\AuditFieldExtension'
        tags:
            - { name: oro_migration.extension, extension_name: audit_field }

    oro_dataaudit.segment_widget.context_checker:
        class: Oro\Bundle\DataAuditBundle\SegmentWidget\ContextChecker
            - { name: 'oro_migration.extension', extension_name: 'audit_field' }

    oro_dataaudit.set_new_audit_version:
        class: 'Oro\Bundle\DataAuditBundle\Service\SetNewAuditVersionService'
        arguments: ['@doctrine.orm.entity_manager']

    oro_dataaudit.find_or_create_audit:
        class: 'Oro\Bundle\DataAuditBundle\Service\FindOrCreateAuditService'
        arguments: ['@doctrine.orm.entity_manager', '@oro_dataaudit.loggable.audit_entity_mapper']

    oro_dataaudit.get_entity_audit_metadata:
        class: 'Oro\Bundle\DataAuditBundle\Service\GetEntityAuditMetadataService'
        arguments: ['@oro_entity_config.provider.dataaudit']

    oro_dataaudit.get_human_readable_entity_name:
        class: 'Oro\Bundle\DataAuditBundle\Service\GetHumanReadableEntityNameService'
        arguments:
            - '@doctrine'
            - '@oro_entity.entity_name_resolver'

    oro_dataaudit.convert_change_set_to_audit_fields:
        class: 'Oro\Bundle\DataAuditBundle\Service\ConvertChangeSetToAuditFieldsService'
        arguments:
            - '@oro_dataaudit.get_human_readable_entity_name'

    oro_dataaudit.convert_entity_changes_to_audit:
        class: 'Oro\Bundle\DataAuditBundle\Service\ConvertEntityChangesToAuditService'
        arguments:
            - '@doctrine'
            - '@oro_dataaudit.set_new_audit_version'
            - '@oro_dataaudit.find_or_create_audit'
            - '@oro_dataaudit.get_entity_audit_metadata'
            - '@oro_dataaudit.get_human_readable_entity_name'
            - '@oro_dataaudit.convert_change_set_to_audit_fields'

    oro_dataaudit.async.audit_changed_entities:
        class: 'Oro\Bundle\DataAuditBundle\Async\AuditChangedEntitiesProcessor'
        arguments:
            - '@doctrine'
            - '@oro_dataaudit.convert_entity_changes_to_audit'
            - '@oro_message_queue.message_producer'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_dataaudit.async.audit_changed_entities_relations:
        class: 'Oro\Bundle\DataAuditBundle\Async\AuditChangedEntitiesRelationsProcessor'
        arguments:
            - '@doctrine'
            - '@oro_dataaudit.convert_entity_changes_to_audit'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_dataaudit.async.audit_changed_entities_inverse_relations:
        class: 'Oro\Bundle\DataAuditBundle\Async\AuditChangedEntitiesInverseRelationsProcessor'
        arguments:
            - '@doctrine'
            - '@oro_dataaudit.convert_entity_changes_to_audit'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
